-- DRUCKA orders table — run in Supabase SQL Editor (Dashboard → SQL).
create table if not exists public.orders (
  id text primary key,                          -- DRK-xxxx (generated by frontend)
  created_at timestamptz not null default now(),
  customer jsonb not null,                      -- { name, phone, email, address1..., pincode, notes }
  items jsonb not null,                         -- cart items incl. design layers (data URLs)
  total integer not null,
  payment_mode text,                            -- prepaid | cod
  payment_status text not null default 'Payment Pending',
  qikink_status text not null default 'Draft',  -- Draft → Sent to Qikink → In Production → Shipped → Delivered / Failed
  qikink_order_id text,                         -- saved after /api/qikink/create-order
  tracking_number text,                         -- saved by /api/qikink/order-status
  courier text,
  artwork_urls jsonb not null default '[]',     -- Cloudinary URLs after upload
  notes text
);

create index if not exists orders_qikink_status_idx on public.orders (qikink_status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- Lock the table down: NO public policies. Only the service-role key
-- (used by the Vercel functions) can read/write — exactly what we want.
alter table public.orders enable row level security;
