-- ════════════════════════════════════════════════════════════════════
-- DRUCKA staging bootstrap — paste into a NEW Supabase project, run once.
--
-- GENERATED by scripts/build-staging-bootstrap.mjs from, in order:
--   supabase/schema.sql · schema-update.sql (DDL only) ·
--   product-map-seed.sql · schema-redesign.sql
-- Do not hand-edit: change the source file and regenerate, so staging and
-- production are built from the same statements.
--
-- schema-update.sql ships a seed that writes REPLACE_ME as every
-- qikink_product_id; it is left out here, because product-map-seed.sql
-- carries the real Qikink ids the app actually sends.
--
-- Every statement is idempotent — safe to re-run.
-- ════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────
-- 1 · base schema (schema.sql)
-- ─────────────────────────────────────────────────────────────────
-- DRUCKA orders table — run in Supabase SQL Editor (Dashboard → SQL).
create table if not exists public.orders (
  id text primary key,                          -- DRK-xxxx (generated by frontend)
  created_at timestamptz not null default now(),
  customer jsonb not null,                      -- { name, phone, email, address1..., pincode, notes }
  items jsonb not null,                         -- cart items incl. design layers (data URLs)
  total integer not null,
  payment_mode text,                            -- prepaid | cod
  payment_status text not null default 'Payment Pending',
  qikink_status text not null default 'Draft',  -- Draft → Sent to Qikink → In Production → Shipped → Delivered / Failed
  qikink_order_id text,                         -- saved after /api/qikink/create-order
  tracking_number text,                         -- saved by /api/qikink/order-status
  courier text,
  artwork_urls jsonb not null default '[]',     -- Cloudinary URLs after upload
  notes text
);

create index if not exists orders_qikink_status_idx on public.orders (qikink_status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- Lock the table down: NO public policies. Only the service-role key
-- (used by the Vercel functions) can read/write — exactly what we want.
alter table public.orders enable row level security;

-- ─────────────────────────────────────────────────────────────────
-- 2 · launch update — DDL only (schema-update.sql)
-- ─────────────────────────────────────────────────────────────────
-- DRUCKA launch update — run AFTER schema.sql in Supabase SQL Editor.

-- Razorpay payment columns + error surface
alter table public.orders
  add column if not exists razorpay_order_id text,
  add column if not exists razorpay_payment_id text,
  add column if not exists paid_at timestamptz,
  add column if not exists last_error text;

create index if not exists orders_razorpay_order_idx on public.orders (razorpay_order_id);

-- Editable Qikink product mapping (managed from the Drucka admin panel)
create table if not exists public.product_map (
  drucka_id text primary key,            -- tshirt | oversized | polo | kids-tshirt | hoodie | mug ...
  product_name text not null,
  qikink_product_id text not null,       -- from Qikink dashboard
  sku_pattern text not null,             -- e.g. MRnHs-{color}-{size}
  print_method text not null default 'DTG',  -- DTG | DTF | Embroidery | Sublimation
  colors jsonb not null default '[]',
  sizes jsonb not null default '[]',
  base_cost integer not null default 0,
  shipping_cost integer not null default 0,
  print_areas jsonb not null default '[]',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.product_map enable row level security;
-- No public policies: only the service-role key (Vercel functions) writes.
-- GET /api/admin/product-map proxies reads to the frontend.

-- ─────────────────────────────────────────────────────────────────
-- 3 · product map seed (product-map-seed.sql)
-- ─────────────────────────────────────────────────────────────────
-- Seed public.product_map from the map the app actually ships with
-- (QIKINK_PRODUCT_MAP in src/App.jsx). Generated - do not hand-edit; regenerate
-- from the app instead, so the automated path and the admin button agree.
--
-- The seed in schema-update.sql is NOT this: it writes REPLACE_ME as every
-- qikink_product_id and carries stale SKU stems, which is worse than an empty
-- table - fulfillFromDb would find a mapping and send Qikink a product id that
-- does not exist. Run schema-update.sql for the DDL, then this for the data.
--
-- Re-running RESETS active to the values below (on conflict ... do update).
-- So if you enable a row in the database, flip it here too, or the next run
-- of this file will quietly switch it back off.

insert into public.product_map
  (drucka_id, product_name, qikink_product_id, sku_pattern, print_method, colors, sizes, base_cost, shipping_cost, print_areas, active)
values
  ('tshirt', 'Regular T-Shirt', 'MRNHS-180', 'MRnHs-{color}-{size}', 'DTG', '["white","black","navy","red","royal-blue","bottle-green","maroon","yellow","lavender","baby-pink"]', '["S","M","L","XL","XXL","3XL","4XL","5XL","6XL","7XL"]', 359, 49, '["Front","Back","Left chest"]', true),
  ('oversized', 'Oversized T-Shirt', 'UC22', 'UOsMRnHs-{color}-{size}', 'DTF', '["white","black","navy"]', '["S","M","L","XL","XXL"]', 419, 49, '["Front","Back"]', true),
  ('polo', 'Polo T-Shirt', 'MP25', 'MPHs-{color}-{size}', 'Embroidery', '["white","black","navy"]', '["S","M","L","XL","XXL"]', 449, 49, '["Left chest"]', false),
  -- Both kids stems ship INACTIVE. Their size tokens (0_12 … 13Yrs) and the
  -- per-stem colour codes (BRnHs has no plain Yellow, KHd spells baby pink
  -- BPk) are verified against the sku_descriptions export but not yet against
  -- the live Qikink account. They gate together: BRnHs and KHd differ only in
  -- stem and colour codes, so confirming one confirms the other.
  --   Enable after confirming:
  --     update public.product_map set active = true
  --      where drucka_id in ('kids-tshirt','kids-hoodie');
  -- Until then keep both hidden from checkout — a sellable product with no
  -- active mapping becomes a paid order that fails "No active product mapping".
  ('kids-tshirt', 'Kids T-Shirt', 'US21', 'BRnHs-{color}-{size}', 'DTG', '["white","yellow","baby-pink","royal-blue","red"]', '["0–12M","12–23M","24–35M","36–47M","5Y","7Y","9Y","11Y","13Y"]', 329, 49, '["Front","Back"]', false),
  ('kids-hoodie', 'Kids Hoodie', 'KHd', 'KHd-{color}-{size}', 'DTF', '["black","red","yellow","baby-pink"]', '["0–12M","12–23M","24–35M","36–47M","5Y","7Y","9Y","11Y","13Y"]', 495, 49, '["Front","Back"]', false),
  ('hoodie', 'Hoodie', 'UH24', 'UHd-{color}-{size}', 'DTF', '["white","black","navy","maroon","bottle-green"]', '["S","M","L","XL","XXL","3XL"]', 649, 69, '["Front","Back"]', true),
  ('mug', 'Photo Mug', 'UWCM', 'UWCM-{color}-11 OZ', 'Sublimation', '["white"]', '["325 ml"]', 179, 49, '["Wrap"]', true),
  ('frame', 'Framed Print', 'UFPos', 'UFPos-{color}-{size}', 'Sublimation', '["black","white"]', '["A4","A3"]', 350, 49, '["Front"]', true),
  ('poster', 'Poster Print', 'UPoster', 'UPoster-{color}-{size}', 'Sublimation', '["white"]', '["A3","12×18\"","24×36\""]', 80, 49, '["Front"]', true),
  ('canvas', 'Stretched Canvas', 'UCanvas', 'UCanvas-{color}-{size}', 'Sublimation', '["white"]', '["8×8\"","8×12\"","16×20\"","20×30\""]', 300, 49, '["Front"]', true),
  ('stickers', 'Custom Stickers', 'UStickers', 'UStickers-{color}-{size}', 'Sublimation', '["white"]', '["2×2\"","3×3\"","4×4\"","6×6\"","8×8\""]', 25, 49, '["Front"]', true),
  ('cushion', 'Photo Cushion', 'UAopCuCvr', 'UAopCuCvr-{color}-{size}', 'All over', '["white"]', '["16\""]', 140, 49, '["Front"]', true),
  ('invitation-cards', 'Invitation Cards', 'UGrtCr', 'UGrtCr-{color}-{size}', 'Sublimation', '["white"]', '["A5 Print"]', 30, 49, '["Front"]', true),
  ('keychain', 'Acrylic Keychain', 'UAcryKyChnUV', 'UAcryKyChnUV-{color}-{size}', 'Sublimation', '["white"]', '["Standard"]', 60, 49, '["Front"]', true)
on conflict (drucka_id) do update set
  product_name = excluded.product_name,
  qikink_product_id = excluded.qikink_product_id,
  sku_pattern = excluded.sku_pattern,
  print_method = excluded.print_method,
  colors = excluded.colors,
  sizes = excluded.sizes,
  base_cost = excluded.base_cost,
  shipping_cost = excluded.shipping_cost,
  print_areas = excluded.print_areas,
  active = excluded.active,
  updated_at = now();

-- ─────────────────────────────────────────────────────────────────
-- 4 · order-lifecycle redesign (schema-redesign.sql)
-- ─────────────────────────────────────────────────────────────────
-- ════════════════════════════════════════════════════════════════════
-- DRUCKA order-lifecycle redesign — Phase 1 (Schema)
-- Run in Supabase SQL Editor AFTER schema.sql and schema-update.sql.
-- Implements ADR-0001 (see REDESIGN.md) §10 file 1.
--
-- Fully idempotent + additive: safe to re-run, and safe to apply to a LIVE
-- database while the old app is still running (no existing row is rewritten,
-- the status CHECK is added NOT VALID so current 'Draft' writes still pass).
-- ════════════════════════════════════════════════════════════════════

-- ── 1. Retry bookkeeping on orders ──────────────────────────────────
-- fulfill_attempts : how many times fulfillFromDb() has failed for this order.
-- next_retry_at    : when the worker/cron may next attempt fulfillment.
alter table public.orders
  add column if not exists fulfill_attempts integer not null default 0,
  add column if not exists next_retry_at   timestamptz;

-- ── 2. Fulfillment-queue index ──────────────────────────────────────
-- The cron drain query is:
--   qikink_status IN ('Ready','Failed')
--   AND payment_status IN ('Paid','COD Approved')
--   AND (next_retry_at IS NULL OR next_retry_at <= now())
--   AND fulfill_attempts < 6
-- A partial index keyed on next_retry_at, limited to the two pickup states,
-- keeps that sweep cheap even as the table grows.
create index if not exists orders_fulfillment_queue_idx
  on public.orders (next_retry_at)
  where qikink_status in ('Ready', 'Failed');

-- ── 3. Status "enum" via CHECK (the canonical qikink_status set) ─────
-- qikink_status stays a text column (the app uses string literals), but this
-- constraint documents + guards the allowed values. It includes the LEGACY
-- 'Draft' so the currently-deployed app keeps working; a later phase can drop
-- 'Draft' and run `VALIDATE CONSTRAINT` once no code writes it anymore.
-- NOT VALID => enforced on new/updated rows, existing rows left untouched.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'orders_qikink_status_chk'
  ) then
    alter table public.orders
      add constraint orders_qikink_status_chk
      check (qikink_status in (
        'Draft',            -- legacy (pre-redesign); removable after cutover
        'Queued',           -- saved, COD awaiting approval
        'Ready',            -- approved / paid — enqueued for the worker
        'Sending',          -- worker holds the lock; Qikink call in flight
        'Sent to Qikink',   -- success
        'In Production',    -- downstream (status poll)
        'Shipped',          -- downstream (status poll)
        'Delivered',        -- downstream (status poll)
        'Failed',           -- attempt failed, attempts < 6, retry pending
        'Dead Letter'       -- attempts >= 6, terminal until manual rescue
      ))
      not valid;
  end if;
end $$;

-- ── 4. Per-order event timeline (observability) ─────────────────────
-- One row per lifecycle event, e.g. 'Order Created', 'COD Approved',
-- 'Worker Picked', 'Upload Success', 'Qikink Accepted', 'Qikink Failed'.
-- Written best-effort by api/_lib/events.js (Phase 2); the orders row stays
-- the source of truth, so an events insert failure never blocks fulfillment.
create table if not exists public.order_events (
  id         bigint generated always as identity primary key,
  order_id   text not null references public.orders(id) on delete cascade,
  event      text not null,
  detail     jsonb,
  created_at timestamptz not null default now()
);

create index if not exists order_events_order_idx
  on public.order_events (order_id, created_at);

-- Lock it down like orders/product_map: service-role key only, no public policy.
alter table public.order_events enable row level security;

-- ─────────────────────────────────────────────────────────────────
-- VERIFY — expect 2, 1, 1, 5, 14 mappings, 0 placeholders
-- ─────────────────────────────────────────────────────────────────
select
  (select count(*) from information_schema.columns
     where table_name='orders' and column_name in ('fulfill_attempts','next_retry_at')) as columns_expect_2,
  (select count(*) from pg_indexes
     where tablename='orders' and indexname='orders_fulfillment_queue_idx') as index_expect_1,
  (select count(*) from pg_constraint where conname='orders_qikink_status_chk') as constraint_expect_1,
  (select count(*) from information_schema.columns where table_name='order_events') as event_cols_expect_5,
  (select count(*) from public.product_map) as mappings_expect_14,
  (select count(*) from public.product_map where qikink_product_id = 'REPLACE_ME') as placeholders_expect_0;
